server:
  port: 8090
spring:
  application:
    name: "loans" # este es el nombre de la aplicación, el cuál se mostrarará en el tablero de eureka
  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud: # configuration of circuitbreaker-resilience4j
    openfeign:
      circuitbreaker:
        alphanumeric-ids:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"  # le indica al actuator de spring cloud que referesque las propiedades en tiempo de ejecución
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  info:
    env:
      enabled: true

#--------------------------------------------- Información del Microservicio ---------------------------------------------#
info:
  app:
    name: "loans"
    description: "uarciac Loans Application"
    version: "1.0.0"

endpoints:
  shutdown:
    enabled: true

#--------------------------------------------- CONFIG EUREKA SERVER ---------------------------------------------#
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


logging:
  level:
    com:
      example:
        loans: DEBUG

#--------------------------------------------- configuration of circuitbreaker-resilience4j ---------------------------------------------#
resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 2
      failureRateThreshold: 50
      waitDurationInOpenState: 10000
