server:
  port: 8080
spring:
  application:
    name: "accounts"
  profiles:
    active: "prod"
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassname: org.h2.Driver
    username: sa
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  config:
    import: "optional:configserver:http://localhost:8071/"
  cloud: # configuration of circuitbreaker-resilience4j
    openfeign:
      circuitbreaker:
        alphanumeric-ids:
          enabled: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
    info:
      env:
        enabled: true

endpoints:
  shutdown:
    enabled: true

#--------------------------------------------- CONFIG EUREKA SERVER ---------------------------------------------#
eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/

info:
  app:
    name: "accounts_ms"
    description: "uarciac Accounts Application"
    version: "1.0.01"

logging:
  level:
    com:
      ulisesgc:
        accounts: DEBUG

#--------------------------------------------- configuration of circuitbreaker-resilience4j ---------------------------------------------#
resilience4j.circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 2
        failureRateThreshold: 50
        waitDurationInOpenState: 10000
