spring:
  application:
    name: "configserver"
  profiles:
    active: git
  # active: native # for config defined in files class_path server, not used with repo git
  cloud:
    config:
      server:
        #native:
          #search-locations: "file:///Volumes//Disk//Documents//04_WORKSPACE//WORKSPACE_SPRING//v2-spring-cloud-config//config"
          #search-locations: "classpath:/config" cuando los archivos son tomados del classpath
          git:
            uri: "https://github.com/ugarciacalderon/config.git"
            default-label: main
            timeout: 5 #seconds
            clone-on-start: true
            force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
encrypt:
  key: "4L0SRSFIKOTG77TQQGF7SI07B5ZJZ1"

server:
  port: 8071
